// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseLayout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"h-full bg-slate-50\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/ui/base.templ`, Line: 9, Col: 26}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"/static/css/app.css\"><script src=\"https://unpkg.com/htmx.org@1.9.12\" defer></script><script src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\" defer></script></head><body class=\"min-h-full font-sans text-slate-900\"><div id=\"app\" class=\"min-h-screen flex flex-col\"><header class=\"border-b border-slate-200 bg-white/95 backdrop-blur-md sticky top-0 z-40\"><div class=\"container\"><div class=\"flex items-center justify-between py-4\"><div class=\"flex items-center gap-3\"><div class=\"h-10 w-10 rounded-lg bg-slate-900 text-white flex items-center justify-center font-semibold tracking-tight\">U</div><div><p class=\"text-sm uppercase tracking-[0.2em] text-slate-500\">Scrapy Labs</p><p class=\"text-lg font-semibold tracking-tight text-slate-900\">UAE Cost of Living</p></div></div><div class=\"hidden md:flex items-center gap-6 text-sm text-slate-600\"><a href=\"#estimator\" class=\"hover:text-slate-900\">Estimator</a> <a href=\"#insights\" class=\"hover:text-slate-900\">Insights</a> <a href=\"#data\" class=\"hover:text-slate-900\">Raw Data</a></div><div class=\"text-xs uppercase tracking-[0.3em] text-slate-400\">Live data</div></div></div></header><main class=\"flex-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><footer class=\"bg-slate-900 text-slate-200 py-10 mt-20\"><div class=\"container grid gap-6 md:grid-cols-3\"><div><p class=\"text-xs uppercase tracking-[0.2em] text-slate-400\">About</p><p class=\"mt-2 text-sm text-slate-300\">Scrapy keeps UAE expats updated with live housing, utilities, and transport costs powered by our crawler fleet.</p></div><div><p class=\"text-xs uppercase tracking-[0.2em] text-slate-400\">Stack</p><ul class=\"mt-2 text-sm text-slate-300 space-y-1\"><li>Go + Echo + Temporal</li><li>Templ + HTMX + Alpine</li><li>Postgres + Timescale</li></ul></div><div><p class=\"text-xs uppercase tracking-[0.2em] text-slate-400\">Status</p><p class=\"mt-2 text-sm text-slate-300\">Automated scrapers run on cadence; UI updates instantly through HTMX requests.</p></div></div></footer></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
