// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package data

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
)

type BarChartConfig struct {
	ID          string
	Title       string
	Description string
	Labels      []string
	Datasets    []ChartDataset
	Height      string
	Stacked     bool
	Horizontal  bool
	ShowLegend  bool
	ShowExport  bool
}

type ChartDataset struct {
	Label           string
	Data            []float64
	BackgroundColor string
	BorderColor     string
}

// BarChart creates a Chart.js bar chart for cost comparisons
func BarChart(config BarChartConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<canvas id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(config.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/ui/components/data/bar-chart.templ`, Line: 37, Col: 17}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" x-data=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(`{
				chart: null,
				init() {
					const ctx = document.getElementById('%s').getContext('2d');
					this.chart = new Chart(ctx, {
						type: '%s',
						data: {
							labels: %s,
							datasets: %s
						},
						options: {
							responsive: true,
							maintainAspectRatio: false,
							indexAxis: '%s',
							plugins: {
								legend: {
									display: %t,
									position: 'top',
									labels: {
										font: {
											family: 'Inter, sans-serif',
											size: 12
										},
										padding: 16,
										usePointStyle: true
									}
								},
								tooltip: {
									backgroundColor: 'rgba(15, 23, 42, 0.95)',
									titleFont: {
										family: 'Inter, sans-serif',
										size: 13,
										weight: '600'
									},
									bodyFont: {
										family: 'Inter, sans-serif',
										size: 12
									},
									padding: 12,
									cornerRadius: 8,
									displayColors: true,
									callbacks: {
										label: function(context) {
											let label = context.dataset.label || '';
											if (label) {
												label += ': ';
											}
											if (context.parsed.y !== null) {
												label += new Intl.NumberFormat('en-US', {
													style: 'currency',
													currency: 'AED'
												}).format(context.parsed.y);
											}
											return label;
										}
									}
								}
							},
							scales: {
								x: {
									stacked: %t,
									grid: {
										display: false
									},
									ticks: {
										font: {
											family: 'Inter, sans-serif',
											size: 11
										}
									}
								},
								y: {
									stacked: %t,
									beginAtZero: true,
									grid: {
										color: 'rgba(148, 163, 184, 0.1)'
									},
									ticks: {
										font: {
											family: 'Inter, sans-serif',
											size: 11
										},
										callback: function(value) {
											return new Intl.NumberFormat('en-US', {
												style: 'currency',
												currency: 'AED',
												minimumFractionDigits: 0
											}).format(value);
										}
									}
								}
							},
							interaction: {
								intersect: false,
								mode: 'index'
							}
						}
					});

					// Store chart instance globally for export
					window.charts = window.charts || {};
					window.charts['%s'] = this.chart;
				},
				destroy() {
					if (this.chart) {
						this.chart.destroy();
					}
				}
			}`, config.ID, chartType(config.Horizontal), labelsJSON(config.Labels), datasetsJSON(config.Datasets), indexAxis(config.Horizontal), config.ShowLegend, config.Stacked, config.Stacked, config.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/ui/components/data/bar-chart.templ`, Line: 146, Col: 197}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" x-init=\"init()\" x-destroy=\"destroy()\"></canvas>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ChartWrapper(ChartConfig{
			ID:          config.ID,
			Title:       config.Title,
			Description: config.Description,
			Height:      config.Height,
			ShowExport:  config.ShowExport,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func chartType(horizontal bool) string {
	return "bar"
}

func indexAxis(horizontal bool) string {
	if horizontal {
		return "y"
	}
	return "x"
}

func labelsJSON(labels []string) string {
	// This would properly marshal to JSON
	return "[]"
}

func datasetsJSON(datasets []ChartDataset) string {
	// This would properly marshal to JSON with colors
	return "[]"
}

var _ = templruntime.GeneratedTemplate
