// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package navigation

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// This file contains example usage of all navigation components
// Use these as reference when implementing navigation in your application

// ExampleNavbarUsage shows how to use the complete navbar component
func ExampleNavbarUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = NavbarComplete(NavbarCompleteProps{
			LogoText:    "My Application",
			Subtitle:    "Built with Templ",
			ShowStatus:  true,
			StatusText:  "Live",
			StatusColor: "green",
			NavLinks: []NavLink{
				{Href: "/", Text: "Home", Label: "Navigate to home page"},
				{Href: "/about", Text: "About", Label: "Navigate to about page"},
				{Href: "/products", Text: "Products", Label: "Navigate to products page"},
				{Href: "/contact", Text: "Contact", Label: "Navigate to contact page"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleBreadcrumbUsage shows how to use the breadcrumb component
func ExampleBreadcrumbUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 py-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Breadcrumb(BreadcrumbProps{
			Items: []BreadcrumbItem{
				{Text: "Products", Href: "/products"},
				{Text: "Electronics", Href: "/products/electronics"},
				{Text: "Laptops", Href: "/products/electronics/laptops"},
				{Text: "MacBook Pro", Href: ""}, // Last item (current page) doesn't need href
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleBreadcrumbCompactUsage shows the compact breadcrumb for mobile
func ExampleBreadcrumbCompactUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"container mx-auto px-4 py-4\"><!-- Show compact version on mobile, full on desktop --><div class=\"md:hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BreadcrumbCompact(BreadcrumbProps{
			Items: []BreadcrumbItem{
				{Text: "Products", Href: "/products"},
				{Text: "Electronics", Href: "/products/electronics"},
				{Text: "Laptops", Href: "/products/electronics/laptops"},
				{Text: "MacBook Pro", Href: ""},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"hidden md:block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Breadcrumb(BreadcrumbProps{
			Items: []BreadcrumbItem{
				{Text: "Products", Href: "/products"},
				{Text: "Electronics", Href: "/products/electronics"},
				{Text: "Laptops", Href: "/products/electronics/laptops"},
				{Text: "MacBook Pro", Href: ""},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleTabsBasicUsage shows basic tab usage with inline content
func ExampleTabsBasicUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"container mx-auto px-4 py-8\"><h2 class=\"text-2xl font-bold mb-4\">Product Information</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "overview",
			Variant:    "underline",
			Size:       "md",
			UseHTMX:    false,
			Tabs: []TabItem{
				{
					ID:      "overview",
					Label:   "Overview",
					Icon:    "📋",
					Content: TabContent("This is the overview section with product details."),
				},
				{
					ID:      "specs",
					Label:   "Specifications",
					Icon:    "⚙️",
					Content: TabContent("Technical specifications go here."),
				},
				{
					ID:      "reviews",
					Label:   "Reviews",
					Icon:    "⭐",
					Badge:   "12",
					Content: TabContent("Customer reviews and ratings."),
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleTabsPillsVariant shows tabs with pills variant
func ExampleTabsPillsVariant() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"container mx-auto px-4 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "all",
			Variant:    "pills",
			Size:       "md",
			UseHTMX:    false,
			Tabs: []TabItem{
				{
					ID:      "all",
					Label:   "All",
					Content: TabContent("All items are shown here."),
				},
				{
					ID:      "active",
					Label:   "Active",
					Badge:   "5",
					Content: TabContent("Active items only."),
				},
				{
					ID:      "completed",
					Label:   "Completed",
					Content: TabContent("Completed items."),
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleTabsHTMXUsage shows tabs with HTMX for dynamic content loading
func ExampleTabsHTMXUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"container mx-auto px-4 py-8\"><h2 class=\"text-2xl font-bold mb-4\">Dynamic Content Tabs</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab:    "dashboard",
			Variant:       "underline",
			Size:          "md",
			UseHTMX:       true,
			HTMXTarget:    "tab-content",
			HTMXIndicator: "loading",
			Tabs: []TabItem{
				{
					ID:    "dashboard",
					Label: "Dashboard",
					Icon:  "📊",
					Href:  "/api/tabs/dashboard",
				},
				{
					ID:    "analytics",
					Label: "Analytics",
					Icon:  "📈",
					Href:  "/api/tabs/analytics",
				},
				{
					ID:    "settings",
					Label: "Settings",
					Icon:  "⚙️",
					Href:  "/api/tabs/settings",
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleTabsBoxedVariant shows tabs with boxed variant
func ExampleTabsBoxedVariant() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"container mx-auto px-4 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "preview",
			Variant:    "boxed",
			Size:       "lg",
			UseHTMX:    false,
			Tabs: []TabItem{
				{
					ID:      "preview",
					Label:   "Preview",
					Content: TabContent("Preview your changes here."),
				},
				{
					ID:      "code",
					Label:   "Code",
					Content: TabContent("View the code implementation."),
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleMobileMenuUsage shows standalone mobile menu usage
func ExampleMobileMenuUsage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"p-4\"><h3 class=\"text-lg font-bold mb-4\">Mobile Menu Example</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MobileMenuComplete(
			[]NavLink{
				{Href: "/", Text: "Home", Label: "Go to home"},
				{Href: "/products", Text: "Products", Label: "View products"},
				{Href: "/about", Text: "About", Label: "Learn about us"},
				{Href: "/contact", Text: "Contact", Label: "Contact us"},
			},
			"MyApp",
			"Navigation",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ExampleFullPageLayout shows a complete page layout with all navigation components
func ExampleFullPageLayout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<!doctype html><html lang=\"en\" class=\"h-full\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Navigation Components Example</title><script src=\"https://cdn.tailwindcss.com\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><style>\n\t\t\t\t[x-cloak] { display: none !important; }\n\t\t\t\t.htmx-indicator { display: none; }\n\t\t\t\t.htmx-request .htmx-indicator { display: flex; }\n\t\t\t</style></head><body class=\"h-full bg-slate-50 dark:bg-slate-950\"><!-- Navbar -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = NavbarComplete(NavbarCompleteProps{
			LogoText:    "Component Demo",
			Subtitle:    "Templ + Alpine.js",
			ShowStatus:  true,
			StatusText:  "Live",
			StatusColor: "green",
			NavLinks: []NavLink{
				{Href: "#navbar", Text: "Navbar", Label: "Navigate to navbar section"},
				{Href: "#breadcrumb", Text: "Breadcrumb", Label: "Navigate to breadcrumb section"},
				{Href: "#tabs", Text: "Tabs", Label: "Navigate to tabs section"},
				{Href: "#examples", Text: "Examples", Label: "Navigate to examples section"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<!-- Main Content --><main class=\"container mx-auto px-4 py-8\"><!-- Breadcrumb Example --><section id=\"breadcrumb\" class=\"mb-12\"><h2 class=\"text-3xl font-bold mb-6 text-slate-900 dark:text-white\">Breadcrumb Navigation</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Breadcrumb(BreadcrumbProps{
			Items: []BreadcrumbItem{
				{Text: "Components", Href: "/components"},
				{Text: "Navigation", Href: "/components/navigation"},
				{Text: "Examples", Href: ""},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</section><!-- Tabs Example --><section id=\"tabs\" class=\"mb-12\"><h2 class=\"text-3xl font-bold mb-6 text-slate-900 dark:text-white\">Tab Navigation</h2><div class=\"bg-white dark:bg-slate-900 rounded-lg shadow-sm p-6 border border-slate-200 dark:border-slate-800\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "overview",
			Variant:    "underline",
			Size:       "md",
			UseHTMX:    false,
			Tabs: []TabItem{
				{
					ID:      "overview",
					Label:   "Overview",
					Icon:    "📋",
					Content: TabContent("Welcome to the navigation components demo. These components are built with Templ, Alpine.js, and Tailwind CSS."),
				},
				{
					ID:      "features",
					Label:   "Features",
					Icon:    "✨",
					Content: TabContent("Features include: responsive design, dark mode support, keyboard navigation, ARIA labels, and smooth transitions."),
				},
				{
					ID:      "usage",
					Label:   "Usage",
					Icon:    "📖",
					Badge:   "New",
					Content: TabContent("Check the examples.templ file for complete usage examples and implementation details."),
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</div></section><!-- Pills Variant Example --><section class=\"mb-12\"><h3 class=\"text-2xl font-bold mb-4 text-slate-900 dark:text-white\">Pills Variant</h3><div class=\"bg-white dark:bg-slate-900 rounded-lg shadow-sm p-6 border border-slate-200 dark:border-slate-800\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "all",
			Variant:    "pills",
			Size:       "md",
			UseHTMX:    false,
			Tabs: []TabItem{
				{ID: "all", Label: "All Items", Content: TabContent("All items view")},
				{ID: "active", Label: "Active", Badge: "5", Content: TabContent("Active items view")},
				{ID: "archived", Label: "Archived", Content: TabContent("Archived items view")},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</div></section><!-- Boxed Variant Example --><section class=\"mb-12\"><h3 class=\"text-2xl font-bold mb-4 text-slate-900 dark:text-white\">Boxed Variant</h3><div class=\"bg-slate-100 dark:bg-slate-800 rounded-lg p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Tabs(TabsProps{
			DefaultTab: "preview",
			Variant:    "boxed",
			Size:       "md",
			UseHTMX:    false,
			Tabs: []TabItem{
				{ID: "preview", Label: "Preview", Content: TabContent("Preview your content here")},
				{ID: "code", Label: "Code", Content: TabContent("View the source code")},
				{ID: "output", Label: "Output", Content: TabContent("See the rendered output")},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</div></section></main><!-- Footer --><footer class=\"border-t border-slate-200 dark:border-slate-800 mt-12 py-8\"><div class=\"container mx-auto px-4 text-center text-slate-600 dark:text-slate-400\"><p>Built with Templ + Alpine.js + HTMX + Tailwind CSS</p></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
